<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Sera.Core\Sera.Core.csproj" />
    <ProjectReference Include="..\Sera.Data\Sera.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NodaTime" Version="3.1.11" />
    <PackageReference Include="JsonSchema.Net" Version="7.0.2" />
    <PackageReference Include="Quartz" Version="3.18.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
